export const Users = [
  {
    id: 1,
    profilePicture: "/src/assets/profiles/1.jpg",
    username: "John Smith",
  },
  {
    id: 2,
    profilePicture: "/src/assets/profiles/2.jpg",
    username: "James Christ",
  },
  {
    id: 3,
    profilePicture: "/src/assets/profiles/3.jpg",
    username: "John Carter",
  },
  {
    id: 4,
    profilePicture: "/src/assets/profiles/4.jpg",
    username: "sarah Ali",
  },
  {
    id: 5,
    profilePicture: "/src/assets/profiles/5.jpg",
    username: "Thomas Holden",
  },
  {
    id: 6,
    profilePicture: "/src/assets/profiles/6.jpg",
    username: "Enma Watson",
  },
  {
    id: 7,
    profilePicture: "/src/assets/profiles/7.jpg",
    username: "Travis Bennett",
  },
  {
    id: 8,
    profilePicture: "/src/assets/profiles/8.jpg",
    username: "Kristen",
  },
  {
    id: 9,
    profilePicture: "/src/assets/profiles/9.jpg",
    username: "Gary Duty",
  },
  {
    id: 10,
    profilePicture: "/src/assets/profiles/10.jpg",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "/src/assets/posts/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Food is an Emotion Enjoy Everybite.",
    photo: "/src/assets/posts/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "/src/assets/posts/3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    desc: "Exploring the Nature.",
    photo: "/src/assets/posts/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    desc: "Cinematic Photography",
    photo: "/src/assets/posts/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    desc: "Skin care products for the smooth skin.",
    photo: "/src/assets/posts/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "/src/assets/posts/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "Build up your mind and maintain Consistency.",
    photo: "/src/assets/posts/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "/src/assets/posts/9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "/src/assets/posts/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
